baseURL = 'https://notes.tomgoren.com/'
languageCode = 'en-us'
title = 'Tom Goren'
theme = "hextra"
staticDir = ['static']
enableEmoji = true

[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 1


[params]
description = "Thoughts and stuff"

[params.navbar]
displayTitle = true
displayLogo = false

[params.navbar.logo]
path = "images/fish_and_prawn.jpg"
dark = "images/fish_and_prawn.jpg"
link = "/"
width = 34
height = 34

[params.theme]
default = "dark"
displayToggle = true

[params.search]
enable = false

[params.analytics.umami]
serverURL = "https://cloud.umami.is"
websiteID = "dd5fc939-9e67-4ad1-ad02-394ba2070e7b"
scriptName = "script.js"

[params.author]
name = "Tom Goren"
email = "tom@tomgoren.com"

[markup.goldmark.renderer]
unsafe = true
